name: flame_loading_progress
description: Flame extension to add widgets with progress bar and transition animation
version: 0.0.1+1
repository: https://github.com/ASGAlex/flame_loading_progress

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flame: ^1.6.0
  flame_message_stream: ^0.0.1
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
