name: flame_loading_progress
description: Flame extension to add widgets with progress bar and transition animation
version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.6.0
  flame_message_stream:
    git: git@github.com:ASGAlex/flame_message_stream.git
  flutter:
    sdk: flutter
  meta: 1.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
